nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: sonatype/nexus3
  tag: ""
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: 4000Mi

persistence:
  enabled: true
  volumeName: nexus
  claimName: nexus
  mountPath: /nexus-data
  subPath: nexus-data

hostname: nexus

service:
  type: ClusterIP
  port: 8081

ingress:
  host: nexus.example.com
