nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: sonatype/nexus3
  tag: ""
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: 4Gi

volumeMounts: null

volumes: null

hostname: nexus

service:
  type: ClusterIP
  port: 8081

ingress:
  host: null
