nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: sonatype/nexus3
  tag: ""
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: 4Gi

volumeMounts:
  - name: nexus
    mountPath: /nexus-data
    subPath: nexus-data

volumes:
  - name: nexus
    persistentVolumeClaim:
      claimName: nexus

hostname: nexus

service:
  type: ClusterIP
  port: 8081

ingress:
  host: nexus.example.com
