{{- if .Values.service -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus.fullname" . }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "nexus.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  {{- if .Values.service.ports }}
  ports:
{{ toYaml .Values.service.ports | indent 4 }}
  {{- end }}
{{- end }}